//DEFINICIÓN VISUAL DE LOS BLOQUES 
        Blockly.defineBlocksWithJsonArray([
            //Bloques de Funciones Básicas
            {
                "type": "bloque_pintar",
                "message0": "pintar()",
                "previousStatement": null,
                "nextStatement": null,
                "colour": 130,
                "tooltip": "Pinta la casilla actual."
            },
            {
                "type": "bloque_subir",
                "message0": "subir()",
                "previousStatement": null,
                "nextStatement": null,
                "colour": 130,
                "tooltip": "Mueve el pincel hacia arriba."
            },
            {
                "type": "bloque_bajar",
                "message0": "bajar()",
                "previousStatement": null,
                "nextStatement": null,
                "colour": 130,
                "tooltip": "Mueve el pincel hacia abajo."
            },
            {
                "type": "bloque_derecha",
                "message0": "derecha()",
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 130,
                "tooltip" : "Mueve el pincel hacia la derecha."
            },
            {
                "type": "bloque_izquierda",
                "message0": "izquierda()",
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 130,
                "tooltip" : "Mueve el pincel hacia la izquierda."
            },

            //Bloques de Color
            {
                "type": "bloque_seleccionarColor",
                "message0": "seleccionarColor( %1 )",
                args0: [
                    {
                        "type": "field_dropdown",
                        "name": "COLOR",
                        "options": [
                            ["Negro", "black"],
                            ["Blanco", "white"],
                            ["Azul Alicia", "aliceblue"],
                            ["Blanco Antiguo", "antiquewhite"],
                            ["Agua", "aqua"],
                            ["Aguamarina", "aquamarine"],
                            ["Azur", "azure"],
                            ["Beige", "beige"],
                            ["Crema", "bisque"],
                            ["Almendra Blanqueada", "blanchedalmond"],
                            ["Azul", "blue"],
                            ["Azul Violeta", "blueviolet"],
                            ["Marrón", "brown"],
                            ["Madera Sólida", "burlywood"],
                            ["Azul Cadete", "cadetblue"],
                            ["Verde Amarillento (Chartreuse)", "chartreuse"],
                            ["Chocolate", "chocolate"],
                            ["Coral", "coral"],
                            ["Azul Aciano", "cornflowerblue"],
                            ["Pelo de Choclo", "cornsilk"],
                            ["Carmesí", "crimson"],
                            ["Cian", "cyan"],
                            ["Azul Oscuro", "darkblue"],
                            ["Cian Oscuro", "darkcyan"],
                            ["Vara de Oro Oscuro", "darkgoldenrod"],
                            ["Gris Oscuro", "darkgray"],
                            ["Verde Oscuro", "darkgreen"],
                            ["Caqui Oscuro", "darkkhaki"],
                            ["Magenta Oscuro", "darkmagenta"],
                            ["Verde Oliva Oscuro", "darkolivegreen"],
                            ["Naranja Oscuro", "darkorange"],
                            ["Orquídea Oscuro", "darkorchid"],
                            ["Rojo Oscuro", "darkred"],
                            ["Salmón Oscuro", "darksalmon"],
                            ["Verde Mar Oscuro", "darkseagreen"],
                            ["Azul Pizarra Oscuro", "darkslateblue"],
                            ["Gris Pizarra Oscuro", "darkslategray"],
                            ["Turquesa Oscuro", "darkturquoise"],
                            ["Violeta Oscuro", "darkviolet"],
                            ["Rosa Profundo", "deeppink"],
                            ["Azul Cielo Profundo", "deepskyblue"],
                            ["Gris Tenue", "dimgray"],
                            ["Azul Dodger", "dodgerblue"],
                            ["Ladrillo Refractario", "firebrick"],
                            ["Blanco Floral", "floralwhite"],
                            ["Verde Bosque", "forestgreen"],
                            ["Fucsia", "fuchsia"],
                            ["Gris Gainsboro", "gainsboro"],
                            ["Blanco Fantasma", "ghostwhite"],
                            ["Oro", "gold"],
                            ["Vara de Oro", "goldenrod"],
                            ["Gris", "gray"],
                            ["Verde", "green"],
                            ["Verde Amarillo", "greenyellow"],
                            ["Rocío de Miel", "honeydew"],
                            ["Rosa Cálido", "hotpink"],
                            ["Rojo Indio", "indianred"],
                            ["Índigo", "indigo"],
                            ["Marfil", "ivory"],
                            ["Caqui", "khaki"],
                            ["Lavanda", "lavender"],
                            ["Rubor Lavanda", "lavenderblush"],
                            ["Verde Césped", "lawngreen"],
                            ["Gasa de Limón", "lemonchiffon"],
                            ["Azul Claro", "lightblue"],
                            ["Coral Claro", "lightcoral"],
                            ["Cian Claro", "lightcyan"],
                            ["Amarillo Vara de Oro Claro", "lightgoldenrodyellow"],
                            ["Gris Claro", "lightgrey"],
                            ["Verde Claro", "lightgreen"],
                            ["Rosa Claro", "lightpink"],
                            ["Salmón Claro", "lightsalmon"],
                            ["Verde Mar Claro", "lightseagreen"],
                            ["Azul Cielo Claro", "lightskyblue"],
                            ["Gris Pizarra Claro", "lightslategray"],
                            ["Azul Acero Claro", "lightsteelblue"],
                            ["Amarillo Claro", "lightyellow"],
                            ["Lima", "lime"],
                            ["Verde Lima", "limegreen"],
                            ["Lino", "linen"],
                            ["Magenta", "magenta"],
                            ["Granate", "maroon"],
                            ["Aguamarina Medio", "mediumaquamarine"],
                            ["Azul Medio", "mediumblue"],
                            ["Orquídea Medio", "mediumorchid"],
                            ["Púrpura Medio", "mediumpurple"],
                            ["Verde Mar Medio", "mediumseagreen"],
                            ["Azul Pizarra Medio", "mediumslateblue"],
                            ["Verde Primavera Medio", "mediumspringgreen"],
                            ["Turquesa Medio", "mediumturquoise"],
                            ["Rojo Violeta Medio", "mediumvioletred"],
                            ["Azul Medianoche", "midnightblue"],
                            ["Crema de Menta", "mintcream"],
                            ["Rosa Brumoso", "mistyrose"],
                            ["Mocasín", "moccasin"],
                            ["Blanco Navajo", "navajowhite"],
                            ["Azul Marino", "navy"],
                            ["Encaje Antiguo", "oldlace"],
                            ["Oliva", "olive"],
                            ["Verde Oliva Pardo", "olivedrab"],
                            ["Naranja", "orange"],
                            ["Naranja Rojizo", "orangered"],
                            ["Orquídea", "orchid"],
                            ["Vara de Oro Pálido", "palegoldenrod"],
                            ["Verde Pálido", "palegreen"],
                            ["Turquesa Pálido", "paleturquoise"],
                            ["Rojo Violeta Pálido", "palevioletred"],
                            ["Crema de Papaya", "papayawhip"],
                            ["Polvo de Durazno", "peachpuff"],
                            ["Marrón Rojizo (Perú)", "peru"],
                            ["Rosa", "pink"],
                            ["Ciruela", "plum"],
                            ["Azul Pólvora", "powderblue"],
                            ["Púrpura", "purple"],
                            ["Púrpura Rebecca", "rebeccapurple"],
                            ["Rojo", "red"],
                            ["Marrón Rosado", "rosybrown"],
                            ["Azul Real", "royalblue"],
                            ["Marrón Silla", "saddlebrown"],
                            ["Salmón", "salmon"],
                            ["Marrón Arena", "sandybrown"],
                            ["Verde Mar", "seagreen"],
                            ["Concha Marina", "seashell"],
                            ["Siena", "sienna"],
                            ["Plata", "silver"],
                            ["Azul Cielo", "skyblue"],
                            ["Azul Pizarra", "slateblue"],
                            ["Gris Pizarra", "slategray"],
                            ["Nieve", "snow"],
                            ["Verde Primavera", "springgreen"],
                            ["Azul Acero", "steelblue"],
                            ["Tostado", "tan"],
                            ["Verde Azulado", "teal"],
                            ["Cardo", "thistle"],
                            ["Tomate", "tomato"],
                            ["Turquesa", "turquoise"],
                            ["Violeta", "violet"],
                            ["Trigo", "wheat"],
                            ["Humo Blanco", "whitesmoke"],
                            ["Amarillo", "yellow"],
                            ["Amarillo Verdoso", "yellowgreen"]
                        ]
                    }
                ],
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 40,
                "tooltip" : "Selecciona el color del pincel."
            },
            {
                "type": "bloque_siguienteColor",
                "message0": "siguienteColor()",
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 40,
                "tooltip" : "Cambia el color al siguiente de la lista."
            },
            {
                "type": "bloque_colorRandom",
                "message0": "colorRandom()",
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 40,
                "tooltip" : "Selecciona un color al azar"
            },
            {
                "type": "bloque_colores",
                "message0": "colores()",
                "previousStatement": null,
                "nextStatement" : null,
                "colour" : 40,
                "tooltip" : "Ver los colores disponibles"
            },

            //Bloques de Sensores
            {
                "type": "bloque_estaPintado",
                "message0": "estaPintado()",
                "output": null,
                "colour" : 0,
                "tooltip" : "Verifica que el bloque esté pintado"
            },
            {
                "type": "bloque_colorCelda",
                "message0": "colorCelda()",
                "output": null,
                "colour" : 0,
                "tooltip" : "Retorna el color de la celda"
            },
            {
                "type": "bloque_colorActivo",
                "message0": "colorActivo()",
                "output": null,
                "colour" : 0,
                "tooltip" : "Retorna el color que está utilizando el pincel"
            },
            {
                "type": "bloque_posicionX",
                "message0": "posicionX()",
                "output": null,
                "colour" : 0,
                "tooltip" : "Retorna la posición X del pincel"
            },
            {
                "type": "bloque_posicionY",
                "message0": "posicionY()",
                "output": null,
                "colour" : 0,
                "tooltip" : "Retorna la posición Y del pincel"
            }
        ]);
